### ISSUE TITLE
v2-dev: `skipEmpty` still includes empty arrays/objects

### ISSUE THREAD

**Issue by KES777** [brainfoolong/form-data-json#16]
**Describe the bug**
When nested form fields are not filled, they are included anyway

**To Reproduce**
```
	<input name = "client[name]">
	<input name = "client[edrpou]">

	<input name = "client[person][0][phone][]">
	<input name = "client[person][0][phone][]">
	<input name = "client[person][0][phone][]">


	<input name = "client[person][0][email][]">
	<input name = "client[person][0][email][]">


	<input name = "client[person][1][phone][]">
	<input name = "client[person][1][phone][]">

	<input name = "client[person][1][email][]">
	<input name = "client[person][1][email][]">
	<input name = "client[person][1][email][]">
	<select name="client[status][]" id="cars" multiple>
	  <option value="volvo">Volvo</option>
	  <option value="saab">Saab</option>
	  <option value="opel">Opel</option>
	  <option value="audi">Audi</option>
	</select>

	<input type="checkbox" name="scales[]">
	<input type="checkbox" name="scales[]" checked value="77">
```

![image](https://user-images.githubusercontent.com/799021/134916418-a90d5eea-bd80-4191-972e-c8eee8775508.png)

**Comment by KES777** [comment]
Empty multiselect is returned even if `skipEmtpy` is true

![image](https://user-images.githubusercontent.com/799021/134916686-d7fece31-23e9-4132-a562-deb1a624a56c.png)

**Comment by KES777** [comment]
And at this case not all values are returned. I expect array of `email` and `phone` values (html code is above):

![image](https://user-images.githubusercontent.com/799021/134917401-d684bbcc-0182-423b-a478-a1466c08710f.png)

**Comment by KES777** [comment]
Not all form values are returned when `flatList` is true

![image](https://user-images.githubusercontent.com/799021/134919205-70042eda-2a20-48b2-b659-cbf3041c8513.png)

Expected:
When `flatList` there array of fields with theirs values should be returned:
```javascript
[
   'client[person][0][phone][]', 'yy',
   'client[person][0][phone][]', 'zz',
]
```

And vice-verse we can supply array field names with theirs values to `.fromJson`

**Comment by brainfoolong** [comment]
Thx for report.

`skipEmpty` now works in 2.0.3beta - All empty (empty array, empty fields) are deleted before output
`flatList` now works in 2.0.3beta as suggested, same keys as native FormData would have

**Comment by KES777** [comment]
Why array of arrays instead of even sized array of key, value? I do not know where this already used, but it seems overkill.

In any case items with empty value should not be returned: `docn`, `docdate`
![image](https://user-images.githubusercontent.com/799021/134964343-795f4d3b-22a9-4e8b-85c0-9d1d7407a730.png)

**Comment by brainfoolong** [comment]
The `flatList` now is considered to reproduce `FormData`. Key 0 is always the input name, Key 1 is always the value of the input. If it is a multiple field, than it's for sure an array value.

Combination of flatList and skipEmpty still seems buggy, i'll look into that.

**Comment by brainfoolong** [comment]
Combination of flatList and skipEmpty is fixed in latest commit.

**Comment by KES777** [comment]
No names for fields are returned:

![image](https://user-images.githubusercontent.com/799021/135045394-67cd0304-5af3-4b39-8799-85a453094c32.png)

**Comment by brainfoolong** [comment]
Thanks. Lol. I need a break :) I come to you when i have something new.

**Comment by brainfoolong** [comment]
Ok, there was a glitch, this should be fixed in latest commit in v2 (No release created yet)

**Comment by KES777** [comment]
working well, thank you ;-)

**Comment by brainfoolong** [comment]
Nice. Thx.
