### ISSUE TITLE
Implement FormDataGraphQL

### ISSUE THREAD

**Issue by KES777** [brainfoolong/form-data-json#23]
**Is your feature request related to a problem? Please describe.**
Hi. We have complex forms. For example Company have multiple emails, phones. While we can send this at object like:
```
{ Company => { name => 'x', phones => [{ phone => '1234' },{ phone => '12345' }], emails => [{...},{...}] } }
```
We want to do same thing via `GraphQL`

It would be nice if `FormDataJson` will be able to send this data at GraphQL format

**Describe the solution you'd like**
https://graphql.org/

**Comment by brainfoolong** [comment]
Hi, thanks for reaching out again, but sorry - No way to get this in this library.

This library is only intended for JSON usage (As the library name speaks for itself). Furthermore, GraphQL is no data format, it is a query language. It would be the same to ask to implement "Mysql" output into this library, which makes also no sense.

You must write your own abstraction layer, if you need to built GraphQL queries out of some form data.

**Comment by brainfoolong** [comment]
Sorry, this is no language that i've ever used.
