### ISSUE TITLE
Automatic array processing while fromJson

### ISSUE THREAD

**Issue by Nazar84** [brainfoolong/form-data-json#24]
Hi!
I`v got a form and get a data from DB for It. The data has the same structure:
```
{
  Company: [
    {
      id: 2,
      name: 'PanamaServ',
      Address: [
        {
          Country: [
            {
              id: 2,
              name: 'USA',
            },
          ],
          address: 'Porkold 11a',
          city: 'NewYork',
          company_id: 2,
          country_id: 2,
          id: 4,
          post_code: 34246,
          region:'ZP',
        },
      ],
      Email: [
        {
          company_id: 2,
          email: 'doubled@ukr.net',
          id: 3,
        },
        {
          company_id: 2,
          email: 'aii@nnn.net',
          id: 2,
        },
      ],
    },
  ],
}
```
It is necessary to use array because the DB can  returns multiple objects. So therefore I should use corresponding names for input fields of the form:
```
name="Company[0][Address][0][country_id]"
name="Company[0][Email][0][email]"
```
It is inconvenient to get first element  always.

It would be great the _fromJson_ method automatically get first element of an array. And returns callback to process the array in custom function and logging to the console to inform a user if the array has multiple elements.
I think it might looks like:
```
function process_array ( array ) {
    return array[2];
}
```
It Probably needs an option for this behavior.

**Comment by brainfoolong** [comment]
Hi. Thanks for reaching out. Unfortunately i don't see any beneficial use of this. It is completely business logic.

The best way is that you process the data _before_ you pass it to  `fromJson`, as you would do anyway with the callback. It make absolutely no difference if you add a separate callback that handles your business logic inside `fromJson`, or when you do it beforehand and let `fromJson` do it's thing.

It add's no benefit for anybody and just increase complexity of `fromJson` for no real advantage. Everything you want to create here requires manual development of a function that manipulate your data.

**Comment by Nazar84** [comment]
Thanks! I`v got  you and agree with you.
