### ISSUE TITLE
Name syntax with dot 

### ISSUE THREAD

**Issue by Nazar84** [brainfoolong/form-data-json#26]
Hi! Now to specify nesting I have to use '[ ]' in field name.

Maybe It would be more convenient to use '.'
Example (something like this):
```
<input name="Company[Phone][0][phone]" type="text" value="34343">
<input name="Company.Phone[0]phone" type="text" value="34343">
```
Where the data is:
```
{
 Company: {
  Phone: [{
     phone: 34343,
   }],
 },
}
```

**Comment by brainfoolong** [comment]
Hi. A `dot` is invalid - Or let's say, a problem, here. On form submit it get converted to underscore, so this is no option as it would expect names that are absolutely should be avoided in production. It is solely syntactic sugar.

**Comment by Nazar84** [comment]
Ok, I`v got you. Thanks!
