### ISSUE TITLE
radio element value 0

### ISSUE THREAD

**Issue by daralx** [brainfoolong/form-data-json#30]
Hi 

First of all thanks for plugin

I am not filling radio element if its value is 0.  ()
if I convert to string or bigger then 0 it is ok.   
ex : { opened : 0 } not running

<input class="form-check-input" type="radio" name="opened" value="0">

**Comment by brainfoolong** [comment]
Hi, i need an example code to reproduce where you see the problem, Html with the form and javascript part.
