### ISSUE TITLE
how to skip non selected select option

### ISSUE THREAD

**Issue by takeAction** [brainfoolong/form-data-json#31]
I am using `FormDataJson.toJson("#searchForm", {skipEmpty: true})`, but I found that for `select` option:
```
<select name="gender">
	<option value="" selected></option>
	<option value="0" >Male</option>
	<option value="1" >Female</option>
</select>
```
if there is no valid option selected(that is Male or Female in this case), `FormDataJson.toJson("#searchForm", {skipEmpty: true})` still return `gender` with null, what I suppose is to skip `gender`. I tried to change `<option value="" selected></option>` to `<option ></option>`, still not work.

how can I skip non selected `select` element?

**Comment by brainfoolong** [comment]
Thanks for your report. This issue has now been fixed in 2.1.4.

https://github.com/brainfoolong/form-data-json/releases/tag/2.1.4
