### ISSUE TITLE
Use `import` instead of `require`

### ISSUE THREAD

**Issue by KES777** [brainfoolong/form-data-json#33]
**Is your feature request related to a problem? Please describe.**
```
import { FormDataJson as FormDataJson } from "form-data-json-convert/dist/form-data-json";
```
After this line of code `FormDataJson` stays undefined. Is this supported?

**Describe the solution you'd like**
Support modern way of module loading.

**Comment by brainfoolong** [comment]
Hi. `import` is not supported, as `FormDataJson` is not a ES6 module.

**Comment by brainfoolong** [comment]
Support for ES6 modules now added. https://github.com/brainfoolong/form-data-json/releases/tag/2.2.0

**Comment by KES777** [comment]
Thank you very much!

**Comment by KES777** [comment]
Probably your documentation is outdated a bit.
I am using in my code: `import FormDataJson from 'form-data-json-convert';`

But it is documented as: `import FormDataJson from 'pathtodistfolder/form-data-json.es6.js'`

This is how it looks in my `package.json` file:
```
"dependencies": {
  "form-data-json-convert": "^2.2.2",
  ...
}
```

**Comment by brainfoolong** [comment]
Do you use this code in Node JS or in the browser?

**Comment by KES777** [comment]
I use it at NodeJS. I configured my project with help of `package.json` then run `npm run build` to compile libraries and my code into one `project.js` file.
Then I include that file into my HTML pages via `<script>` tag.

**Comment by brainfoolong** [comment]
The note in the readme is still valid for ES6 modules and requires this line if you just want to use it as a module, without using the default script. You can see that in tests example: https://github.com/brainfoolong/form-data-json/blob/master/docs/tests/test-es6.html

**Comment by KES777** [comment]
Probably this works for you project because tests are located at relative folder. But this does not work if FormDataJson is installed via `packet.json`. I am not familiar with JS and I do not know where it installs modules. So I did not managed to find `pathtodistfolder`. It taken me a while to find the `import FormDataJson from 'form-data-json-convert';` solution.

Thanks.

**Comment by brainfoolong** [comment]
It's ok how it is in the Readme. It's on everybody alone where and how they install this library. Some do with npm, some have own folders, some use CDN, some use bundlers, etc... `pathtodistfolder` simple mean you need to know where the file is and how to point to the correct path. 

No need to do further changes in the readme.
