### ISSUE TITLE
Wouldn't it be nicer if toJSON returns promise

### ISSUE THREAD

**Issue by yahyaerturan** [brainfoolong/form-data-json#34]
When converting form it could be take time to convert file fields. I think it would be better if toJson returns a promise so we can be sure that it worked 100% as we use it with `toJson().then()`

**Comment by brainfoolong** [comment]
Hi. fromJson/toJson are synchronous. There is no need to await that. It is guaranteed, the moment the function returns something, that is has done all the work already.

There is only one "async"-like behaviour, the callback parameter when you have file fields as well.

Promises does not bring any useful performance boost here. I have tested it with 1000 fields in one form, no problem.

Also, changing the behaviour of an existing function in such way will bread it for everyone else.

So, all in all, no feature the will be implemented here.

Greetz
