### ISSUE TITLE
Add examples how to name inputs to get nested data

### ISSUE THREAD

**Issue by KES777** [brainfoolong/form-data-json#39]
**Describe the bug**
It looks like the main feature of this library is not highlighted at README.md
I can see that something is here: https://github.com/brainfoolong/form-data-json/blob/master/docs/index.html, but it is not clear how to view that document not in html without dowloading/intalling it locally.

**Comment by brainfoolong** [comment]
Hi. There is a official demo homepage, listed in the Github infos at the right. https://brainfoolong.github.io/form-data-json

**Comment by KES777** [comment]
I am using your library couple of years, but never seen that )
It would be nice if you put that link somewhere here: 
![image](https://github.com/user-attachments/assets/bdc650da-175e-42c0-8948-32980361275d)

**Comment by brainfoolong** [comment]
On Github, it is default that the projects homepage is always in the repository description on the right :)

But maybe i can at the link separately into Readme, just for completeness.

**Comment by KES777** [comment]
After half a year I found documentation through this issue :D.
Still looking for links to `Demo` at README.md =(
