### ISSUE TITLE
Populate multiple checkboxes with the same name (not using []-names)

### ISSUE THREAD

**Issue by powerbuoy** [brainfoolong/form-data-json#41]
I have a form with multiple checkboxes, all named `test` (unfortunately, out of my control, not named `test[]`).

```
<input type="checkbox" name="test" value="foo">
<input type="checkbox" name="test" value="bar">
```

When trying to populate them using data like this `{"test": ["foo", "bar"]}` nothing happens.

Also, when fetching the form data as JSON I also only get the first checkbox.

Is there any way I can get around this problem?

https://codepen.io/powerbuoy/pen/KKOMBee

(NOTE: Changing the name to `test[]` resolves the issue, but again, is impossible for me to do in this case).

**Comment by powerbuoy** [comment]
Well I shouldn't have said _impossible_, because after som more tinkering I indeed managed to stick [] in the name attribute. But could still be useful to know whether or not this is doable _without_ changing the name?

**Comment by brainfoolong** [comment]
Hi. This is not possible with this library. The array syntax is required to make it an array.
