### ISSUE TITLE
NPM Module?

### ISSUE THREAD

**Issue by cybervaldez** [brainfoolong/form-data-json#7]
**Describe the bug**
There's an npm install in the readme but can not import?

**To Reproduce**
```
import FormDataJson from "form-data-json-convert"
const FormDataJson2 = require("form-data-json-convert")

// both returns empty objects
```

**Comment by brainfoolong** [comment]
Yes sorry, npm support is currently not finished. Will do that tomorrow.

**Comment by cybervaldez** [comment]
Awesome! Quite frankly this is the only library out there for converting formdata to nested json.

**Comment by brainfoolong** [comment]
There are a few older libs with jQuery dependency that do similar stuff. But i wanted a dependency free, modernized handling for such things.

By the way. NPM module should now work, starting with version `1.2.2`.
Import demo also in the NPM install usage of the Readme.
